language: python

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.5

notifications:
  email: false

# Setup anaconda
before_install:
  - if [ ${PYTHON_VERSION:0:1} == "2" ];
    then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${PYTHON_VERSION:0:1} == "2" ];
    then export PATH=/home/travis/miniconda2/bin:$PATH;
    else export PATH=/home/travis/miniconda3/bin:$PATH;
    fi
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - pip install python-coveralls
  - conda install --yes atlas numpy scipy matplotlib nose dateutil pandas statsmodels coverage basemap
  - python setup.py install

# start xvfb so plotting doesn't cause crash
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Run test
script:
  - coverage run --source=px4tools setup.py test

# Calculate coverage
after_success:
  - coveralls
