language: python

matrix:
    include:
        - python: "2.7"
          env:
              PYTHON="2.7"
              PATH="/home/travis/miniconda2/bin:$PATH"
              CONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
        - python: "3.5"
          env:
              PYTHON="3.5"
              PATH="/home/travis/miniconda3/bin:$PATH"
              CONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

notifications:
  email: false

# Setup anaconda
before_install:
  - wget $CONDA_URL -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - pip install python-coveralls
  - conda install --yes numpy scipy matplotlib nose dateutil pandas statsmodels coverage basemap
  - python setup.py install

# start xvfb so plotting doesn't cause crash
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Run test
script:
  - coverage run --source=px4tools setup.py test

# Calculate coverage
after_success:
  - coveralls
