package:
  name: px4tools
  version: 0.2.6

build:
  number: 1
  script:
    - nosetests -sv

requirements:
  build:
    - nose
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib

about:
  summary: This is for px4 flight log analysis.

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
