package:
  name: px4tools
  version: 0.3.1

source:
  git_rev: v0.3.1
  git_url: https://github.com/dronecrew/px4tools.git

build:
  number: 0
  entry_points:
    - px42csv = px4tools.px42csv:main 

requirements:
  build:
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib

about:
  summary: This is for px4 flight log analysis.

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
