package:
  name: px4tools
  version: 0.3.0

source:
  path: ..

build:
  noarch_python: False
  number: 1
  script:
    - nosetests -sv
  entry_points:
    - px42csv = px4tools.px42csv:main 

requirements:
  build:
    - nose
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - scipy
    - basemap
    - pandas
    - matplotlib

about:
  summary: This is for px4 flight log analysis.

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
