package:
  name: px4tools
  # version: "1.0"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools
    - pandas
    - matplotlib
    - scipy
    - basemap

  run:
    - python
    - numpy
    - pandas
    - matplotlib
    - scipy
    - basemap

test:
    requires:
        - nose
    commands:
        - nosetests --exe pyappveyordemo

about:
  home: https://github.com/jgoppert/px4tools
  license: BSD
